# Product

components:
  schemas:
    Product:
      type: object
      required:
        - id
        - title
        - description
        - code
        - price
        - stock
        - sales
        - thumbnail
      properties:
        id:
          type: number
          description: id autogenerado para el Producto
        title:
          type: string
          description: nombre del producto
        description:
          type: string
          description: description del producto
        code:
          type: string
          description: codigo del producto
        price:
          type: number
          description: precio del producto
        stock:
          type: number
          description: stock del producto
        sales:
          type: number
          description: ventas del producto
        thumbnail:
          type: string
          description: thumbnail del producto
      example:
        _id: "639696bb9669fb6b8d8e0ee6",
        id: 1,
        timestamp: "2022-12-10T14:42:02.011Z",
        dateUpdate: "2022-12-10T14:42:02.011Z",
        title: "Poleron No me olvides",
        description: "Poleron modelo No me Olvides",
        code: "P0001",
        price: 20000,
        stock: 100,
        sales: 0,
        thumbnail: "/assets/img/products/ModeloNomeolvides.jpg"
      
